topic_list_tiles:
  type: list
  default: latest|new|unread|top|tags|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile
  description:
    en: "The lists that will be styled with tiles format.  Can be one of latest|new|unread|top|tags|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile"
topic_list_thumbnail:
  type: list
  default: latest|new|unread|top|tags|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile|agenda-mobile
  description:
    en: "The lists that will include thumbnails.  Can be one of latest|new|unread|top|tags|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile|agenda-mobile"
topic_list_excerpt:
  type: list
  default: latest|new|unread|top|tags|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile|agenda-mobile
  description:
    en:  "The lists that will include excerpts.  Can be one of latest|new|unread|top|tags|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile|agenda-mobile"
topic_list_action:
  type: list
  default: latest|new|unread|top|tags|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile|agenda-mobile
  description:
    en:  "PLACEHOLDER, DOESN'T PRESENTLY WORK, WAITING FOR DISCOURSE SUPPORT The lists that will include actions.  Can be one of latest|new|unread|top|tags|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile|agenda-mobile"
topic_list_tiles_transition_time:
  default: 0.5
  type: float
  description:
    en:  "Number of seconds for tiles layout transition on view change (desktop only)"
topic_list_tiles_larger_featured_tiles:
  default: true
  type: bool
  description:
    en: "Make the tiles with featured tags larger"
topic_list_portfolio:
  default: true
  type: bool
  description:
    en: "Enable additional User Activity view for User Portfolio"
topic_list_portfolio_filter_type:
  default: 'tag'
  type: 'enum'
  description:
    en: "Which type of filter should be used to limit Activity Portfolio Topics"
  choices:
    - tag
    - category
topic_list_portfolio_filter_parameter:
  default: ''
  type: string
  description:
    en:  "Enter the tag or category slug (depending of value of filter type setting)"
topic_list_set_category_defaults:
  default: false
  type: bool
  description:
    en:  "Set site topic list display settings as defaults for category topic lists."
topic_list_show_like_on_current_users_posts:
  default: false
  type: bool
  description:
    en:  "Show an inactive like button in topic list items previewing a post created by the current user (non-default Discourse behavior)."
topic_list_excerpt_length:
  default: 200
  description: 
    en:  "Character length of topic excerpts."
topic_list_default_thumbnail:
  default: ''
  type: string
  description:
    en:  "Image URL for default thumbnail if topic thumbnail is inaccessible."
topic_list_default_thumbnail_fallback:
  default: false
  type: bool
  description:
    en:  "Use the default thumbnail when a topic has no previewed image."
topic_list_thumbnail_width:
  default: 100
  type: integer
  description:
    en:  "Width of topic preview thumbnail."
topic_list_thumbnail_height:
  default: 100
  type: integer
  description:
    en: "Height of topic preview thumbnail. (Setting this to 0 will cause TLP to seek the resolution from thumbnail width whilst maintaining the original image's aspect ratio - especially important for tiles view)"
topic_list_previewable_image_width_min:
  default: 100
  type: integer
  description:
    en: "Minimum width of image that can be previewed."
topic_list_previewable_image_height_min:
  default: 100
  type: integer
  description:
    en: "Minimum height of image that can be previewed."
topic_list_thumbnail_first_x_rows:
  default: 0
  type: integer
  description:
    en: "Show thumbnail only for first X rows. Enter 0 to show on all rows."
topic_list_featured_images:
  default: false
  type: bool
  description:
    en: "PLACEHOLDER, FEATURED IMAGES DOESN'T PRESENTLY WORK Enable featured images for non-category routes."
topic_list_featured_images_full_res:
  default: false
  type: bool
  description:
    en: "Force featured images to use full size original images (use with caution wrt user bandwidth as ignores user pref)"
topic_list_featured_images_category:
  default: false
  type: bool
  description:
    en: "Apply featured images site setting to all categories."
topic_list_featured_images_topic:
  default: false
  type: bool
  description:
    en: "Show featured images above topics."
topic_list_featured_images_tag:
  type: list
  default: ''
  description:
    en: "Featured images tag."
topic_list_featured_images_tag_show:
  default: true
  type: bool
  description:
    en: "Show featured images tag below featured images."
topic_list_featured_images_count:
  default: 4
  description:
    en: "Featured images count."
topic_list_featured_width:
  default: 100
  description:
    en: "Featured image width.  Setting this to zero will make it responsive to image aspect ratio."
topic_list_featured_height:
  default: 100
  description:
    en: "Featured image height."
topic_list_featured_title:
  default: ''
  type: string
  description:
    en: "Featured images title. Supports Markdown."
topic_list_featured_excerpt:
  default: true
  type: bool
  description:
    en: "Include topic excerpt in featured image."
topic_list_featured_order:
  default: 'tag'
  type: 'enum'
  description:
    en: "Order featured images by when topic was created, or featured tag was applied."
  choices:
    - tag
    - topic
topic_list_test_image_url_timeout:
  default: 5000
  type: integer
  description:
    en: "Timeout for testing image url"
topic_list_fade_in_time:
  default: 0
  type: integer
  description:
    en: "Optional fade in of Topic Lists in milliseconds.  0 means OFF"
